---
title: "Instructions for Executing R scripts for Assignment 1"
author: "John Lancaster"
date: "May 6, 2016"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Instructions for Executing plot1, plot2, plot3, plot4 for Assignment 1 
Each of the four R scripts for Assignement #1 reside in the repo you just downloaded from GitHub.

To execute these R scripts you will need to follow the following steps.

  Let  Rscript == the R script you want to execute (plot1, plot2, plot3, plot4).
  
  
  STEP 1: Fork the repo and make a local copy on your computer prior to executing any of the scripts.
          Record the directory path to the repo.
          This only has to be done once. It is not necessary to do this for each execution.
  
  STEP 2: Open Rscript (plot1.R, plot2.R, plot3.R, or plot4.R) in your local repo copy. 

  STEP 3: Edit the directory path listed in the first line to the path of your local repo copy.
          The line in the original R script reads:
          workdir <- "C:/Users/John Lancaster/Desktop/Coursera/Exploratory Analysis/Week 1 Assignment/repo"
          Change the right hand side by copying in your path.
          
  STEP 4: Save and close the editted Rscript file in your local repo copy.
  
  STEP 5: Open RStudio.
  
  STEP 6: On the Menu Bar at the top of your RStudio session open the CODE dropdown list and select SOURCE FILE.
          Click on SOURCE this will open a dialogue for selecting the R script you wish to execute.
          
  STEP 7: Navigate to your local repo copy and select the script you wish to execute, Rscript. Click on it.
          This will execute Rscript. Upon successful execution you will see the plot displayed in your session's PLOTS window. The plot will also have been copied to your copy of repo.
          
  STEP 8: Repeat this STEP 2 through STEP 7 for each plot in the assignment.
